name = equip_wear
title = Equipment Wear
description = Allows tool & equipment wear to be enabled or disabled.
author = Jordan Irwin (AntumDeluge)
license = MIT
version = 0.1
min_minetest_version = 0.4.16
